import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { clsx } from 'clsx';
import { Typography } from '../../atoms/Typography';
import { Button } from '../../atoms/Button';
import styles from './Reconnect.module.css';
/**
 * Reconnection screen with glitch effects.
 * Shown when connection to server is lost.
 */
export function Reconnect({ state, attempts = 0, maxAttempts = 5, errorMessage, onRetry, onNewGame, className, }) {
    return (_jsxs("div", { className: clsx(styles.reconnect, styles[state], className), children: [_jsxs("div", { className: styles.glitchBg, children: [_jsx("div", { className: styles.scanlines }), _jsx("div", { className: styles.noise })] }), _jsxs("div", { className: styles.container, children: [_jsx("div", { className: styles.iconContainer, children: _jsxs("div", { className: styles.icon, children: [_jsxs("svg", { viewBox: "0 0 24 24", className: styles.wifiIcon, children: [_jsx("path", { fill: "currentColor", d: "M12 21l-1.5-1.5c-2.1-2.1-2.1-5.5 0-7.6l1.5-1.5 1.5 1.5c2.1 2.1 2.1 5.5 0 7.6L12 21zm0-4.5c.8 0 1.5.7 1.5 1.5s-.7 1.5-1.5 1.5-1.5-.7-1.5-1.5.7-1.5 1.5-1.5z" }), _jsx("path", { fill: "currentColor", d: "M12 3C7.95 3 4.21 4.34 1.2 6.6l1.5 1.5C5.25 6.05 8.45 5 12 5s6.75 1.05 9.3 3.1l1.5-1.5C19.79 4.34 16.05 3 12 3zm0 4c-2.84 0-5.45.95-7.6 2.55l1.5 1.5C7.75 9.75 9.8 9 12 9s4.25.75 6.1 2.05l1.5-1.5C17.45 7.95 14.84 7 12 7z", className: styles.signalBars })] }), state !== 'failed' && _jsx("div", { className: styles.iconGlitch })] }) }), state === 'disconnected' && (_jsxs(_Fragment, { children: [_jsx(Typography, { variant: "h2", className: styles.glitchText, children: _jsx("span", { className: styles.glitchLayer, "data-text": "DISCONNECTED", children: "DISCONNECTED" }) }), _jsx(Typography, { variant: "body", color: "muted", children: "Connection to server lost" })] })), state === 'reconnecting' && (_jsxs(_Fragment, { children: [_jsx(Typography, { variant: "h2", className: styles.glitchText, children: _jsx("span", { className: styles.glitchLayer, "data-text": "RECONNECTING", children: "RECONNECTING" }) }), _jsxs("div", { className: styles.progressContainer, children: [_jsx("div", { className: styles.progressBar, children: _jsx("div", { className: styles.progressFill, style: { width: `${(attempts / maxAttempts) * 100}%` } }) }), _jsxs(Typography, { variant: "caption", color: "muted", children: ["Attempt ", attempts, " of ", maxAttempts] })] })] })), state === 'failed' && (_jsxs(_Fragment, { children: [_jsx(Typography, { variant: "h2", color: "error", className: styles.glitchText, children: _jsx("span", { className: styles.glitchLayer, "data-text": "FAILED", children: "CONNECTION FAILED" }) }), _jsx(Typography, { variant: "body", color: "muted", children: errorMessage || 'Unable to reconnect to the game server.' }), _jsxs("div", { className: styles.actions, children: [_jsx(Button, { variant: "primary", size: "lg", onClick: onRetry, children: "Try Again" }), _jsx(Button, { variant: "ghost", size: "lg", onClick: onNewGame, children: "Start New Game" })] })] }))] })] }));
}
export default Reconnect;
//# sourceMappingURL=Reconnect.js.map